sudo: required
language: python
python: 
 - 3.6

script:
  - git clone https://github.com/uio-profag/coursepage-jekyllcode && mv coursepage-jekyllcode/* && python convert_notebooks.py

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
